service: battleship-api-${env:TEAM_BRANCH_NAME, 'dev'}
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: '*'
  environment:
    GAMES_TABLE_NAME: ${self:resources.Resources.GamesTable.Properties.TableName}
    AWS_DYNAMO_ENDPOINT: ${self:custom.env.${opt:stage, 'dev'}.dynamoEndpoint}
custom:
  env:
    dev:
      dynamoEndpoint: 'http://localhost:8000'
    prod:
      dynamoEndpoint: ''
  dynamodb:
  # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
    # Uncomment only if you already have a DynamoDB running locally
    # noStart: true   
functions:
  createGame:
    handler: createGame/index.handler
    events:
      - httpApi:
          path: /game
          method: post
  placeShip:
    handler: placeShip/index.handler
    events:
      - httpApi:
          path: /placeShip
          method: post          
  joinGame:
    handler: joinGame/index.handler
    events:
      - httpApi:
          path: /joinGame
          method: post        
  attack:
    handler: attack/index.handler
    events:
      - httpApi:
          path: /attack
          method: post          
  startGame:
    handler: startGame/index.handler
    events:
      - httpApi:
          path: /startGame
          method: post      
  gameState:
    handler: gameState/index.handler
    events:
      - httpApi:
          path: /gameState
          method: post    
resources:
  Resources:
    GamesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-games
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
plugins:
  - serverless-offline
  - serverless-dynamodb-local
