service: battleship-api-${env:TEAM_BRANCH_NAME, 'dev'}
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: '*'
  environment:
    GAMES_TABLE_NAME: ${self:resources.Resources.GamesTable.Properties.TableName}
    AWS_PROFILE: default
functions:
  createGame:
    handler: createGame/index.handler
    events:
      - httpApi:
          path: /createGame
          method: post
  joinGame:
    handler: joinGame/index.handler
    events:
      - httpApi:
          path: /joinGame
          method: post     
  placeShip:
    handler: placeShip/index.handler
    events:
      - httpApi:
          path: /placeShip
          method: post      
  startGame:
    handler: startGame/index.handler
    events:
      - httpApi:
          path: /startGame
          method: post        
  attack:
    handler: attack/index.handler
    events:
      - httpApi:
          path: /attack
          method: post                    
resources:
  Resources:
    GamesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-games
        AttributeDefinitions:
          - AttributeName: gameId
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: gameId
            KeyType: HASH
custom:
  dynamodb:
  # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
    # Uncomment only if you already have a DynamoDB running locally
    # noStart: true
plugins:
  - serverless-dynamodb-local
  - serverless-offline
